name = "aoc2025"
description = ""
version = "0.1.0-dev"

authors = ["Christina Unger"]
maintainers = ["Christina Unger <andrea.christina.unger@gmail.com>"]
maintainers-logins = ["cunger"]
licenses = "MIT"
website = ""
tags = ["advent-of-code"]

executables = ["aoc2025"]

[[depends-on]]
utilada = "2.6.0"